### ISSUE TITLE
Mise à jour

### ISSUE THREAD

**Issue by serut** [ZHAJOR/Docker-Phppgadmin#5]
Hello @ZHAJOR,

There is a new version of phppgadmin available there https://github.com/phppgadmin/phppgadmin/releases.
Can you just regenerate your docker image and push it on the docker hub ?

Thanks

**Comment by ZHAJOR** [comment]
Hi @serut 

Thank you for the update, I just built a new image.
I will soon update the postgres-contrib to the lastest version.

**Comment by ZHAJOR** [comment]
Closing the issue

**Comment by serut** [comment]
Merci ! On va tester ça et on revient si on a un problème.  
What is the postgres-contrib ? Another docker image ?

**Comment by ZHAJOR** [comment]
Parfait !
My mistake, I was thinking about postgresql-client which is a package needed for this docker image.
Right now in the Dockerfile I put postgresql-client-9.6, but the 10 (even 11) is available. Shouldn't be a problem for now, but maybe some advance feature of postgres 10 wouldn't work.

**Comment by serut** [comment]
Oh I see. If we look at their website, they say phpPgadmin is compatible with postgres 9.2 so you should not bump that version yet.
