### ISSUE TITLE
 SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty

### ISSUE THREAD

**Issue by harsh244** [ZHAJOR/Docker-Phppgadmin#6]
Initially the container ran fine, now whenver I try to start the container, I see this error and the container exits

**Comment by ZHAJOR** [comment]
Hi,
I just pulled the image, run a container, stop/start without any issue.
As nothing is stored inside it, I would recommend to delete your container and create a new one.
